# Generated by Django 4.2 on 2023-04-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedio',
            name='precisa_receita',
            field=models.CharField(default='Não', max_length=3),
        ),
    ]
